version: "3.8"

services:
    postgres:
        image: postgres:14
        container_name: postgresql
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB_NAME}
            POSTGRES_USER: ${POSTGRES_DB_USER}
            POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
        name: postgres_data
