version: "3.8"

services:
    postgres:
        image: postgres:14
        container_name: postgresql
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB_NAME}
            POSTGRES_USER: ${POSTGRES_DB_USER}
            POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    mongo:
        image: mongo:latest
        container_name: mongodb
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
        driver: local
        name: postgres_data
    mongodb_data:
        driver: local
        name: mongodb_data
    redis_data:
        driver: local
        name: redis_data
