version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        env_file:
            - .env
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        ports:
            - "5672:5672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    rabbitmq_data:
        driver: local
        name: rabbitmq_data
